/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyBadge {
        "variant": 'explicit' | 'default' | 'master' | 'live';
    }
    interface MyCard {
        /**
          * This is the image url
         */
        "img": string;
        "meta": { master: boolean, explicit: boolean, label: string};
        "subtitle": 'JavaScript' | 'TypeScript' | 'Web Components';
        "top": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLMyBadgeElement extends Components.MyBadge, HTMLStencilElement {
    }
    var HTMLMyBadgeElement: {
        prototype: HTMLMyBadgeElement;
        new (): HTMLMyBadgeElement;
    };
    interface HTMLMyCardElement extends Components.MyCard, HTMLStencilElement {
    }
    var HTMLMyCardElement: {
        prototype: HTMLMyCardElement;
        new (): HTMLMyCardElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-badge": HTMLMyBadgeElement;
        "my-card": HTMLMyCardElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface MyBadge {
        "variant"?: 'explicit' | 'default' | 'master' | 'live';
    }
    interface MyCard {
        /**
          * This is the image url
         */
        "img"?: string;
        "meta"?: { master: boolean, explicit: boolean, label: string};
        "subtitle"?: 'JavaScript' | 'TypeScript' | 'Web Components';
        "top"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "my-badge": MyBadge;
        "my-card": MyCard;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-badge": LocalJSX.MyBadge & JSXBase.HTMLAttributes<HTMLMyBadgeElement>;
            "my-card": LocalJSX.MyCard & JSXBase.HTMLAttributes<HTMLMyCardElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
